%!TEX root = ts.tex

\rSec0[parallel.task_block]{Task Block}

\rSec1[parallel.task_block.synopsis]{Header \tcode{<experimental/task_block> synopsis}}

\begin{codeblock}
namespace std::experimental {
inline namespace parallelism_v2 {
  class task_cancelled_exception;

  class task_block;

  template<class F>
    void define_task_block(F&& f);

  template<class f>
    void define_task_block_restore_thread(F&& f);
}
}
\end{codeblock}

\rSec1[parallel.task_block.task_cancelled_exception]{Class \tcode{task_cancelled_exception}}

\begin{codeblock}
namespace std::experimental {
inline namespace parallelism_v2 {

  class task_cancelled_exception : public exception
  {
    public:
      task_cancelled_exception() noexcept;
      virtual const char* what() const noexcept override;
  };
}
}
\end{codeblock}

\pnum The class \tcode{task_cancelled_exception} defines the type of objects
thrown by \tcode{task_block::run} or \tcode{task_block::wait} if they detect
than an exception is pending within the current parallel block. See
\ref{parallel.task_block.exceptions}, below.

